name: "Labeller"

on:
  pull_request:
    types: [opened, reopened]

permissions: write-all

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: 'needs-review'